import { z } from "zod"

import { canonEntryKinds, canonEntryStatuses, canonEvidenceSourceKinds, projectSummarySnapshotKinds } from "../constants/canon"

const confidenceSchema = z.number().min(0).max(1)

export const canonEvidenceSchema = z.object({
  sourceKind: z.enum(canonEvidenceSourceKinds),
  sourceId: z.string().min(1).max(255),
  excerpt: z.string().max(2000).nullable().optional(),
  weight: z.number().min(0).max(1).optional(),
})

export const createCanonEntrySchema = z.object({
  projectId: z.string().min(1),
  kind: z.enum(canonEntryKinds),
  title: z.string().max(160).nullable().optional(),
  content: z.string().min(1).max(4000),
  status: z.enum(canonEntryStatuses).optional(),
  confidence: confidenceSchema.optional(),
  lockedByUser: z.boolean().optional(),
  autoGenerated: z.boolean().optional(),
  validFrom: z.string().datetime().nullable().optional(),
  validUntil: z.string().datetime().nullable().optional(),
  lastVerifiedAt: z.string().datetime().nullable().optional(),
  supersedesEntryId: z.string().nullable().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  evidence: z.array(canonEvidenceSchema).max(24).optional(),
})

export type CreateCanonEntryInput = z.infer<typeof createCanonEntrySchema>

export const updateCanonEntrySchema = z.object({
  kind: z.enum(canonEntryKinds).optional(),
  title: z.string().max(160).nullable().optional(),
  content: z.string().min(1).max(4000).optional(),
  status: z.enum(canonEntryStatuses).optional(),
  confidence: confidenceSchema.optional(),
  lockedByUser: z.boolean().optional(),
  autoGenerated: z.boolean().optional(),
  validFrom: z.string().datetime().nullable().optional(),
  validUntil: z.string().datetime().nullable().optional(),
  lastVerifiedAt: z.string().datetime().nullable().optional(),
  supersedesEntryId: z.string().nullable().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  evidence: z.array(canonEvidenceSchema).max(24).optional(),
})

export type UpdateCanonEntryInput = z.infer<typeof updateCanonEntrySchema>

export const listCanonEntriesQuerySchema = z.object({
  kinds: z.array(z.enum(canonEntryKinds)).max(12).optional(),
  statuses: z.array(z.enum(canonEntryStatuses)).max(12).optional(),
  includeEvidence: z.boolean().optional(),
})

export const createProjectSummarySnapshotSchema = z.object({
  projectId: z.string().min(1),
  kind: z.enum(projectSummarySnapshotKinds),
  content: z.string().min(1).max(12000),
  derivedFrom: z.array(z.string()).max(64).optional(),
  generationMetadata: z.record(z.string(), z.unknown()).optional(),
})
