import type { CanonEntryKind, CanonEntryRow, CanonEntryStatus } from "@relay/shared"

import { toCanonEntryRow } from "../mappers/canon-mapper"
import type { DatabaseProvider } from "../store/provider"
import { encryptTextIfConfigured } from "../utils/encrypted-text"

const CANON_ENTRY_COLS = `id, project_id, kind, title, content, status, confidence, locked_by_user, auto_generated, valid_from, valid_until, last_verified_at, supersedes_entry_id, metadata, created_by, updated_by, created_at, updated_at`

export class CanonEntryRepository {
  constructor(private readonly provider: DatabaseProvider) {}

  async getById(id: string): Promise<CanonEntryRow | null> {
    const rows = await this.provider.query(
      `select ${CANON_ENTRY_COLS}
       from canon_entries
       where id = $1
       limit 1`,
      [id],
    )

    return rows[0] ? toCanonEntryRow(rows[0] as Record<string, unknown>) : null
  }

  async listByProject(projectId: string, options?: {
    kinds?: CanonEntryKind[]
    statuses?: CanonEntryStatus[]
    limit?: number
  }): Promise<CanonEntryRow[]> {
    const conditions = ["project_id = $1"]
    const params: unknown[] = [projectId]
    let paramIndex = 2

    if (options?.kinds?.length) {
      conditions.push(`kind = ANY($${paramIndex}::text[])`)
      params.push(options.kinds)
      paramIndex++
    }

    if (options?.statuses?.length) {
      conditions.push(`status = ANY($${paramIndex}::text[])`)
      params.push(options.statuses)
      paramIndex++
    }

    params.push(options?.limit ?? 100)

    const rows = await this.provider.query(
      `select ${CANON_ENTRY_COLS}
       from canon_entries
       where ${conditions.join(" and ")}
       order by
         locked_by_user desc,
         case status
           when 'active' then 0
           when 'tentative' then 1
           when 'disputed' then 2
           when 'stale' then 3
           when 'resolved' then 4
           else 5
         end asc,
         auto_generated asc,
         confidence desc,
         updated_at desc
       limit $${paramIndex}`,
      params,
    )

    return rows.map((row) => toCanonEntryRow(row as Record<string, unknown>))
  }

  async searchByProject(projectId: string, query: string, options?: {
    kinds?: CanonEntryKind[]
    statuses?: CanonEntryStatus[]
    currentOnly?: boolean
    historicalAt?: string | null
    limit?: number
  }): Promise<CanonEntryRow[]> {
    const conditions = ["project_id = $1"]
    const params: unknown[] = [projectId, query]
    let paramIndex = 3

    conditions.push(`to_tsvector('english', coalesce(title, '') || ' ' || content) @@ websearch_to_tsquery('english', $2)`)

    if (options?.kinds?.length) {
      conditions.push(`kind = ANY($${paramIndex}::text[])`)
      params.push(options.kinds)
      paramIndex++
    }

    if (options?.statuses?.length) {
      conditions.push(`status = ANY($${paramIndex}::text[])`)
      params.push(options.statuses)
      paramIndex++
    }

    if (options?.currentOnly) {
      conditions.push(`status != 'superseded'`)
      conditions.push(`(valid_until is null or valid_until > now())`)
    }

    if (options?.historicalAt) {
      conditions.push(`(valid_from is null or valid_from <= $${paramIndex}::timestamptz)`)
      conditions.push(`(valid_until is null or valid_until > $${paramIndex}::timestamptz)`)
      params.push(options.historicalAt)
      paramIndex++
    }

    params.push(options?.limit ?? 20)

    const rows = await this.provider.query(
      `select ${CANON_ENTRY_COLS}
       from canon_entries
       where ${conditions.join(" and ")}
       order by
         locked_by_user desc,
         ts_rank(to_tsvector('english', coalesce(title, '') || ' ' || content), websearch_to_tsquery('english', $2)) desc,
         confidence desc,
         updated_at desc
       limit $${paramIndex}`,
      params,
    )

    return rows.map((row) => toCanonEntryRow(row as Record<string, unknown>))
  }

  async create(userId: string, input: {
    projectId: string
    kind: CanonEntryKind
    title: string | null
    content: string
    status: CanonEntryStatus
    confidence: number
    lockedByUser: boolean
    autoGenerated: boolean
    validFrom: string | null
    validUntil: string | null
    lastVerifiedAt: string | null
    supersedesEntryId: string | null
    metadata: Record<string, unknown>
  }): Promise<CanonEntryRow> {
    const rows = await this.provider.query(
      `insert into canon_entries (
         project_id, kind, title, content, status, confidence, locked_by_user, auto_generated,
         valid_from, valid_until, last_verified_at, supersedes_entry_id, metadata, created_by, updated_by
       )
       values ($1, $2, $3, $4, $5, $6, $7, $8, $9::timestamptz, $10::timestamptz, $11::timestamptz, $12, $13::jsonb, $14, $14)
       returning ${CANON_ENTRY_COLS}`,
      [
        input.projectId,
        input.kind,
        input.title ? encryptTextIfConfigured(input.title) : null,
        encryptTextIfConfigured(input.content),
        input.status,
        input.confidence,
        input.lockedByUser,
        input.autoGenerated,
        input.validFrom,
        input.validUntil,
        input.lastVerifiedAt,
        input.supersedesEntryId,
        JSON.stringify(input.metadata ?? {}),
        userId,
      ],
    )

    return toCanonEntryRow(rows[0] as Record<string, unknown>)
  }

  async update(userId: string, id: string, patch: {
    kind?: CanonEntryKind
    title?: string | null
    content?: string
    status?: CanonEntryStatus
    confidence?: number
    lockedByUser?: boolean
    autoGenerated?: boolean
    validFrom?: string | null
    validUntil?: string | null
    lastVerifiedAt?: string | null
    supersedesEntryId?: string | null
    metadata?: Record<string, unknown>
  }): Promise<CanonEntryRow> {
    const rows = await this.provider.query(
      `update canon_entries
       set kind = coalesce($2, kind),
           title = case when $3::boolean then null else coalesce($4, title) end,
           content = coalesce($5, content),
           status = coalesce($6, status),
           confidence = coalesce($7, confidence),
           locked_by_user = coalesce($8, locked_by_user),
           auto_generated = coalesce($9, auto_generated),
           valid_from = case when $10::boolean then null else coalesce($11::timestamptz, valid_from) end,
           valid_until = case when $12::boolean then null else coalesce($13::timestamptz, valid_until) end,
           last_verified_at = case when $14::boolean then null else coalesce($15::timestamptz, last_verified_at) end,
           supersedes_entry_id = case when $16::boolean then null else coalesce($17, supersedes_entry_id) end,
           metadata = coalesce($18::jsonb, metadata),
           updated_by = $19,
           updated_at = now()
       where id = $1
       returning ${CANON_ENTRY_COLS}`,
      [
        id,
        patch.kind ?? null,
        patch.title === null,
        patch.title === undefined ? null : patch.title ? encryptTextIfConfigured(patch.title) : null,
        patch.content === undefined ? null : encryptTextIfConfigured(patch.content),
        patch.status ?? null,
        patch.confidence ?? null,
        patch.lockedByUser ?? null,
        patch.autoGenerated ?? null,
        patch.validFrom === null,
        patch.validFrom ?? null,
        patch.validUntil === null,
        patch.validUntil ?? null,
        patch.lastVerifiedAt === null,
        patch.lastVerifiedAt ?? null,
        patch.supersedesEntryId === null,
        patch.supersedesEntryId ?? null,
        patch.metadata ? JSON.stringify(patch.metadata) : null,
        userId,
      ],
    )

    const row = rows[0]
    if (!row) throw new Error("Canon entry not found")
    return toCanonEntryRow(row as Record<string, unknown>)
  }
}
