import { describe, expect, it } from "vitest"

import type { DatabaseProvider, DatabaseRow } from "../store/provider"
import { CanonEntryRepository } from "./canon-entry-repository"

interface CapturedCall {
  text: string
  values: unknown[]
}

function makeFakeProvider(responseRows: DatabaseRow[] = []): {
  provider: DatabaseProvider
  calls: CapturedCall[]
} {
  const calls: CapturedCall[] = []
  const provider: DatabaseProvider = {
    mode: "local",
    async query<T extends DatabaseRow = DatabaseRow>(text: string, values: unknown[] = []): Promise<T[]> {
      calls.push({ text, values })
      return responseRows as T[]
    },
    async transaction<T>(callback: (provider: DatabaseProvider) => Promise<T>): Promise<T> {
      return callback(provider)
    },
  }
  return { provider, calls }
}

describe("CanonEntryRepository", () => {
  it("orders project canon by lock, status, confidence, and freshness", async () => {
    const { provider, calls } = makeFakeProvider([])
    const repo = new CanonEntryRepository(provider)

    await repo.listByProject("proj-1", {
      kinds: ["decision", "objective"],
      statuses: ["active", "tentative"],
    })

    const sql = calls[0]!.text
    expect(sql).toContain("locked_by_user desc")
    expect(sql).toContain("case status")
    expect(sql).toContain("confidence desc")
    expect(sql).toContain("updated_at desc")
    expect(calls[0]!.values).toContainEqual(["decision", "objective"])
    expect(calls[0]!.values).toContainEqual(["active", "tentative"])
  })

  it("maps rows back to canon entries", async () => {
    const row: DatabaseRow = {
      id: "canon-1",
      project_id: "proj-1",
      kind: "decision",
      title: "Use Neon",
      content: "Use Neon for managed Postgres.",
      status: "active",
      confidence: 0.9,
      locked_by_user: true,
      auto_generated: false,
      valid_from: "2026-04-12T00:00:00.000Z",
      valid_until: null,
      last_verified_at: null,
      supersedes_entry_id: null,
      metadata: {},
      created_by: "user-1",
      updated_by: "user-1",
      created_at: "2026-04-12T00:00:00.000Z",
      updated_at: "2026-04-12T00:00:00.000Z",
    }

    const { provider } = makeFakeProvider([row])
    const repo = new CanonEntryRepository(provider)
    const result = await repo.getById("canon-1")

    expect(result).toEqual({
      id: "canon-1",
      projectId: "proj-1",
      kind: "decision",
      title: "Use Neon",
      content: "Use Neon for managed Postgres.",
      status: "active",
      confidence: 0.9,
      lockedByUser: true,
      autoGenerated: false,
      validFrom: "2026-04-12T00:00:00.000Z",
      validUntil: null,
      lastVerifiedAt: null,
      supersedesEntryId: null,
      metadata: {},
      createdBy: "user-1",
      updatedBy: "user-1",
      createdAt: "2026-04-12T00:00:00.000Z",
      updatedAt: "2026-04-12T00:00:00.000Z",
    })
  })

  it("applies currentOnly and historicalAt filters during search", async () => {
    const { provider, calls } = makeFakeProvider([])
    const repo = new CanonEntryRepository(provider)

    await repo.searchByProject("proj-1", "current objective", {
      currentOnly: true,
      historicalAt: "2026-03-01T00:00:00.000Z",
    })

    const sql = calls[0]!.text
    expect(sql).toContain("status != 'superseded'")
    expect(sql).toContain("valid_until is null or valid_until > now()")
    expect(sql).toContain("valid_from is null or valid_from <= $")
    expect(sql).toContain("websearch_to_tsquery")
    expect(calls[0]!.values).toContain("2026-03-01T00:00:00.000Z")
  })
})
