export const PRICING = {
  free: {
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Get started, no card needed",
    cta: "Get Started",
    ctaVariant: "outline" as const,
    features: [
      "Up to 2 active projects",
      "Standard brief depth",
      "MCP access (read + limited write)",
      "30-day history retention",
      "Browser capture",
    ],
  },
  pro: {
    name: "Pro",
    monthlyPrice: 9,
    yearlyPrice: 90,
    badge: "MOST POPULAR",
    description: "For builders who live in AI tools",
    cta: "Get Pro",
    ctaVariant: "primary" as const,
    features: [
      "Up to 10 active projects",
      "Deep brief with full history",
      "Full MCP access (read + write)",
      "365-day history retention",
      "All capture surfaces",
      "Handoff packs (export/share briefs)",
      "Priority support",
    ],
  },
} as const
