export const PRICING = {
  free: {
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Try Relay, no card needed",
    cta: "Get Started",
    ctaVariant: "outline" as const,
    features: [
      "Up to 2 active projects",
      "Conservative autonomy",
      "7-day capture retention",
      "12 basic MCP reads / day",
      "Browser capture across supported AI tools",
    ],
  },
  starter: {
    name: "Starter",
    monthlyPrice: 12,
    yearlyPrice: 122,
    description: "For solo builders who live inside AI tools",
    cta: "Start Starter",
    ctaVariant: "outline" as const,
    features: [
      "Up to 10 active projects",
      "Standard autonomy + autonomous canon",
      "180-day retention, 1,200 captures / mo",
      "200 reads + 12 deep reads / day",
      "Canon-aware compaction",
      "Quick-continuity + full-bootstrap packets",
    ],
  },
  pro: {
    name: "Pro",
    monthlyPrice: 18,
    yearlyPrice: 184,
    badge: "MOST POPULAR",
    description: "Full autonomy, deep continuity, every surface",
    cta: "Get Pro",
    ctaVariant: "primary" as const,
    features: [
      "Up to 20 active projects",
      "Aggressive autonomy + conflict resolution",
      "365-day retention, 3,000 captures / mo",
      "500 reads + 30 deep reads / day",
      "High-quality model for reflections",
      "Priority support",
    ],
  },
} as const
