import type { RepositoryBundle } from "@relay/db"
import type {
  CanonEntryKind,
  CanonEvidenceRow,
  CanonEvidenceSourceKind,
  CanonEntryRow,
  ProjectStateRow,
  ProjectSummarySnapshotRow,
  SessionDigestShape,
} from "@relay/shared"
import { isSameTopic, normalizeText, sortCanonEntriesByPriority, truncateSentence } from "@relay/shared"

import { GEMINI_MODELS, runGeminiJsonWithFallback } from "./gemini-service"

type CanonSignalRisk = "low" | "medium"

interface CanonSignal {
  kind: CanonEntryKind
  content: string
  title: string | null
  confidence: number
  risk: CanonSignalRisk
}

type AutonomyMode = "conservative" | "standard" | "aggressive"

function mergeEvidence(existing: CanonEvidenceRow[], incoming: Array<{
  sourceKind: CanonEvidenceSourceKind
  sourceId: string
  excerpt?: string | null
  weight?: number
}>): Array<{
  sourceKind: CanonEvidenceSourceKind
  sourceId: string
  excerpt?: string | null
  weight?: number
}> {
  const next: Array<{
    sourceKind: CanonEvidenceSourceKind
    sourceId: string
    excerpt?: string | null
    weight?: number
  }> = existing.map((item) => ({
    sourceKind: item.sourceKind,
    sourceId: item.sourceId,
    excerpt: item.excerpt,
    weight: item.weight,
  }))
  const seen = new Set(next.map((item) => `${item.sourceKind}:${item.sourceId}`))

  for (const item of incoming) {
    const key = `${item.sourceKind}:${item.sourceId}`
    if (seen.has(key)) continue
    seen.add(key)
    next.push(item)
  }

  return next.slice(0, 24)
}

function deriveCanonSignals(digest: SessionDigestShape): CanonSignal[] {
  const signals: CanonSignal[] = []

  const push = (kind: CanonEntryKind, values: string[], risk: CanonSignalRisk, confidence = 0.72) => {
    for (const value of values) {
      const normalized = truncateSentence(normalizeText(value), 400)
      if (!normalized) continue
      signals.push({
        kind,
        content: normalized,
        title: null,
        confidence,
        risk,
      })
    }
  }

  if (digest.currentObjectiveDelta) {
    signals.push({
      kind: "objective",
      content: truncateSentence(normalizeText(digest.currentObjectiveDelta), 320),
      title: null,
      confidence: 0.82,
      risk: "low",
    })
  }

  if (digest.recentProgressDelta) {
    signals.push({
      kind: "progress",
      content: truncateSentence(normalizeText(digest.recentProgressDelta), 500),
      title: null,
      confidence: 0.76,
      risk: "low",
    })
  }

  push("decision", digest.newDecisions ?? [], "medium", 0.68)
  push("constraint", digest.newConstraints ?? [], "medium", 0.68)
  push("task", digest.newTasks ?? [], "low", 0.74)

  return signals.filter((signal) => signal.content.length > 0)
}

function isUserProtected(entry: CanonEntryRow): boolean {
  return entry.lockedByUser || !entry.autoGenerated
}

function buildCurrentFocusSummary(state: ProjectStateRow | null, digest: SessionDigestShape): string | null {
  const parts = [
    digest.currentObjectiveDelta ?? state?.currentObjective ?? null,
    digest.recentProgressDelta ?? state?.recentProgress ?? null,
    digest.newTasks?.[0] ?? state?.openTasks?.[0] ?? null,
  ]
    .map((item) => (item ? truncateSentence(normalizeText(item), 240) : null))
    .filter((item): item is string => Boolean(item))

  return parts.length > 0 ? parts.join(" | ") : null
}

function buildProjectSummary(state: ProjectStateRow | null): string | null {
  if (!state) return null

  const lines = [
    state.projectOverview,
    state.currentObjective ? `Objective: ${state.currentObjective}` : null,
    state.recentProgress ? `Progress: ${state.recentProgress}` : null,
    state.decisions[0] ? `Decision: ${state.decisions[0]}` : null,
    state.constraints[0] ? `Constraint: ${state.constraints[0]}` : null,
  ]
    .map((item) => (item ? truncateSentence(normalizeText(item), 320) : null))
    .filter((item): item is string => Boolean(item))

  return lines.length > 0 ? lines.join("\n") : null
}

async function appendEvidence(
  repositories: RepositoryBundle,
  projectId: string,
  canonEntryId: string,
  evidence: Array<{
    sourceKind: CanonEvidenceSourceKind
    sourceId: string
    excerpt?: string | null
    weight?: number
  }>,
) {
  const current = await repositories.canonEvidence.listByEntry(canonEntryId)
  await repositories.canonEvidence.replaceForEntry(projectId, canonEntryId, mergeEvidence(current, evidence))
}

async function supersedeEntry(repositories: RepositoryBundle, userId: string, entry: CanonEntryRow, validUntil: string) {
  await repositories.canonEntries.update(userId, entry.id, {
    status: "superseded",
    validUntil,
    lastVerifiedAt: validUntil,
  })
}

async function upsertObservedSignal(
  repositories: RepositoryBundle,
  userId: string,
  projectId: string,
  signal: CanonSignal,
  evidence: Array<{
    sourceKind: CanonEvidenceSourceKind
    sourceId: string
    excerpt?: string | null
    weight?: number
  }>,
  observedAt: string,
  autonomyMode: AutonomyMode,
) {
  const existing = sortCanonEntriesByPriority(
    await repositories.canonEntries.listByProject(projectId, {
      kinds: [signal.kind],
      statuses: ["active", "tentative", "disputed"],
      limit: 20,
    }),
  )

  const sameTopic = existing.find((entry) => isSameTopic(entry.content, signal.content))
  if (sameTopic) {
    const updated = await repositories.canonEntries.update(userId, sameTopic.id, {
      lastVerifiedAt: observedAt,
      confidence: Math.max(sameTopic.confidence, signal.confidence),
      status:
        sameTopic.status === "tentative" && (signal.risk === "low" || autonomyMode === "aggressive")
          ? "active"
          : sameTopic.status,
    })
    await appendEvidence(repositories, projectId, updated.id, evidence)
    return updated
  }

  const primary = existing[0]

  if (signal.kind === "objective" || signal.kind === "progress") {
    if (primary && isUserProtected(primary) && !isSameTopic(primary.content, signal.content)) {
      const created = await repositories.canonEntries.create(userId, {
        projectId,
        kind: signal.kind,
        title: signal.title,
        content: signal.content,
        status: "tentative",
        confidence: signal.confidence,
        lockedByUser: false,
        autoGenerated: true,
        validFrom: observedAt,
        validUntil: null,
        lastVerifiedAt: observedAt,
        supersedesEntryId: null,
        metadata: { conflictWithEntryId: primary.id, observedBy: "relay-observer" },
      })
      await appendEvidence(repositories, projectId, created.id, evidence)
      return created
    }

    if (primary && !isUserProtected(primary)) {
      await supersedeEntry(repositories, userId, primary, observedAt)
      const created = await repositories.canonEntries.create(userId, {
        projectId,
        kind: signal.kind,
        title: signal.title,
        content: signal.content,
        status: autonomyMode === "conservative" ? "tentative" : "active",
        confidence: signal.confidence,
        lockedByUser: false,
        autoGenerated: true,
        validFrom: observedAt,
        validUntil: null,
        lastVerifiedAt: observedAt,
        supersedesEntryId: primary.id,
        metadata: { observedBy: "relay-observer" },
      })
      await appendEvidence(repositories, projectId, created.id, evidence)
      return created
    }
  }

  const created = await repositories.canonEntries.create(userId, {
    projectId,
    kind: signal.kind,
    title: signal.title,
    content: signal.content,
    status: signal.risk === "low" && autonomyMode !== "conservative" ? "active" : "tentative",
    confidence: signal.confidence,
    lockedByUser: false,
    autoGenerated: true,
    validFrom: observedAt,
    validUntil: null,
    lastVerifiedAt: observedAt,
    supersedesEntryId: null,
    metadata: { observedBy: "relay-observer" },
  })
  await appendEvidence(repositories, projectId, created.id, evidence)
  return created
}

interface ContradictionResult {
  disputed: string[]
  superseded: string[]
  observations: string[]
}

async function detectContradictions(
  repositories: RepositoryBundle,
  userId: string,
  projectId: string,
  newEntries: CanonEntryRow[],
): Promise<void> {
  const activeEntries = sortCanonEntriesByPriority(
    await repositories.canonEntries.listByProject(projectId, {
      statuses: ["active"],
      limit: 30,
    }),
  )

  if (activeEntries.length < 3 || newEntries.length === 0) return

  const existingText = activeEntries
    .slice(0, 20)
    .map((e) => `[${e.kind}] ${e.content}`)
    .join("\n")
  const newText = newEntries.map((e) => `[${e.kind}] ${e.content}`).join("\n")

  const prompt = `Active canon entries:\n${existingText}\n\nNew entries from latest session:\n${newText}\n\nIdentify contradictions between new and existing entries. Return JSON: { "disputed": [ids of existing entries that conflict with new ones], "superseded": [ids of existing entries that are outdated by new ones], "observations": [brief pattern notes] }. Use empty arrays if none found. Existing entry IDs: ${activeEntries.map((e) => e.id).join(", ")}`

  try {
    const result = await runGeminiJsonWithFallback<ContradictionResult>({
      primaryModel: GEMINI_MODELS.adjudication.primary,
      fallbackModel: GEMINI_MODELS.adjudication.fallback,
      systemInstruction: "You detect contradictions and outdated information in a project's knowledge base. Be conservative — only flag clear contradictions, not minor updates.",
      prompt,
      maxInputTokens: GEMINI_MODELS.adjudication.maxInputTokens,
      maxOutputTokens: GEMINI_MODELS.adjudication.maxOutputTokens,
    })

    const validIds = new Set(activeEntries.map((e) => e.id))
    for (const id of result.data.disputed ?? []) {
      if (validIds.has(id)) {
        const entry = activeEntries.find((e) => e.id === id)
        if (entry && !isUserProtected(entry)) {
          await repositories.canonEntries.update(userId, id, { status: "disputed" })
        }
      }
    }
    for (const id of result.data.superseded ?? []) {
      if (validIds.has(id)) {
        const entry = activeEntries.find((e) => e.id === id)
        if (entry && !isUserProtected(entry)) {
          await supersedeEntry(repositories, userId, entry, new Date().toISOString())
        }
      }
    }
  } catch {
    // fire-and-forget
  }
}

export async function observeAndReflectDigestWithRepositories(
  repositories: RepositoryBundle,
  userId: string,
  input: {
    projectId: string
    digest: SessionDigestShape
    sourceId: string
    sourceKind: CanonEvidenceSourceKind
    observedAt: string
    nextState: ProjectStateRow | null
  },
): Promise<{
  updatedEntries: CanonEntryRow[]
  createdSnapshots: ProjectSummarySnapshotRow[]
}> {
  const signals = deriveCanonSignals(input.digest)
  const settings = await repositories.projectSettings.getByProject(input.projectId)
  const autonomyMode = settings?.settings.autonomyMode ?? "standard"
  const evidence = [{
    sourceKind: input.sourceKind,
    sourceId: input.sourceId,
    excerpt: input.digest.summaryShort,
    weight: 0.8,
  }]

  const updatedEntries: CanonEntryRow[] = []
  for (const signal of signals) {
    updatedEntries.push(
      await upsertObservedSignal(repositories, userId, input.projectId, signal, evidence, input.observedAt, autonomyMode),
    )
  }

  // Fire-and-forget: detect contradictions between new and existing canon entries
  void detectContradictions(repositories, userId, input.projectId, updatedEntries)

  const createdSnapshots: ProjectSummarySnapshotRow[] = []

  const summaryParts = [normalizeText(input.digest.summaryShort)]
  if (input.digest.recentProgressDelta) {
    summaryParts.push(`Progress: ${normalizeText(input.digest.recentProgressDelta)}`)
  }
  if (input.digest.currentObjectiveDelta) {
    summaryParts.push(`Objective: ${normalizeText(input.digest.currentObjectiveDelta)}`)
  }
  const enrichedSummary = truncateSentence(summaryParts.join(" "), 800)

  createdSnapshots.push(
    await repositories.projectSummarySnapshots.create(userId, {
      projectId: input.projectId,
      kind: "session_summary",
      content: enrichedSummary,
      derivedFrom: [input.sourceId],
      generationMetadata: {
        sourceKind: input.sourceKind,
        generatedBy: "relay-reflector",
        sessionDate: input.observedAt,
      },
    }),
  )

  const currentFocus = buildCurrentFocusSummary(input.nextState, input.digest)
  if (currentFocus) {
    createdSnapshots.push(
      await repositories.projectSummarySnapshots.create(userId, {
        projectId: input.projectId,
        kind: "current_focus_summary",
        content: currentFocus,
        derivedFrom: [input.sourceId],
        generationMetadata: { sourceKind: input.sourceKind, generatedBy: "relay-reflector" },
      }),
    )
  }

  const projectSummary = buildProjectSummary(input.nextState)
  if (projectSummary) {
    createdSnapshots.push(
      await repositories.projectSummarySnapshots.create(userId, {
        projectId: input.projectId,
        kind: "project_summary",
        content: projectSummary,
        derivedFrom: [input.sourceId],
        generationMetadata: { sourceKind: input.sourceKind, generatedBy: "relay-reflector" },
      }),
    )
  }

  return { updatedEntries, createdSnapshots }
}

export function buildBootstrapCanonView(
  entries: CanonEntryRow[],
  snapshots: ProjectSummarySnapshotRow[],
  state: ProjectStateRow | null,
): {
  state: ProjectStateRow | null
  tentativeEntries: CanonEntryRow[]
  latestProjectSummary: string | null
  latestCurrentFocusSummary: string | null
} {
  const active = sortCanonEntriesByPriority(entries.filter((entry) => entry.status === "active"))
  const tentativeEntries = sortCanonEntriesByPriority(entries.filter((entry) => entry.status === "tentative"))
  const byKind = new Map<CanonEntryKind, CanonEntryRow[]>()
  for (const entry of active) {
    const current = byKind.get(entry.kind) ?? []
    current.push(entry)
    byKind.set(entry.kind, current)
  }

  const latestProjectSummary = snapshots.find((snapshot) => snapshot.kind === "project_summary")?.content ?? null
  const latestCurrentFocusSummary = snapshots.find((snapshot) => snapshot.kind === "current_focus_summary")?.content ?? null

  if (!state) {
    return {
      state,
      tentativeEntries,
      latestProjectSummary,
      latestCurrentFocusSummary,
    }
  }

  return {
    state: {
      ...state,
      projectOverview: state.projectOverview ?? latestProjectSummary,
      currentObjective: byKind.get("objective")?.[0]?.content ?? state.currentObjective,
      recentProgress: byKind.get("progress")?.[0]?.content ?? latestCurrentFocusSummary ?? state.recentProgress,
      decisions: byKind.get("decision")?.map((entry) => entry.content) ?? state.decisions,
      constraints: byKind.get("constraint")?.map((entry) => entry.content) ?? state.constraints,
      openTasks: byKind.get("task")?.map((entry) => entry.content) ?? state.openTasks,
    },
    tentativeEntries,
    latestProjectSummary,
    latestCurrentFocusSummary,
  }
}
