import { describe, expect, it } from "vitest"

import { buildBootstrapCanonView } from "./canon-autonomy-service"

describe("buildBootstrapCanonView", () => {
  it("overlays active canon on top of project state and preserves tentative entries separately", () => {
    const result = buildBootstrapCanonView(
      [
        {
          id: "canon-objective",
          projectId: "proj-1",
          kind: "objective",
          title: null,
          content: "Ship observer-reflector automation.",
          status: "active",
          confidence: 0.8,
          lockedByUser: false,
          autoGenerated: true,
          validFrom: null,
          validUntil: null,
          lastVerifiedAt: null,
          supersedesEntryId: null,
          metadata: {},
          createdBy: "user-1",
          updatedBy: null,
          createdAt: "2026-04-13T00:00:00.000Z",
          updatedAt: "2026-04-13T00:00:00.000Z",
        },
        {
          id: "canon-risk",
          projectId: "proj-1",
          kind: "risk",
          title: null,
          content: "Potential MCP 429 issue remains unresolved.",
          status: "tentative",
          confidence: 0.7,
          lockedByUser: false,
          autoGenerated: true,
          validFrom: null,
          validUntil: null,
          lastVerifiedAt: null,
          supersedesEntryId: null,
          metadata: {},
          createdBy: "user-1",
          updatedBy: null,
          createdAt: "2026-04-13T00:00:00.000Z",
          updatedAt: "2026-04-13T00:00:00.000Z",
        },
      ],
      [
        {
          id: "snap-1",
          projectId: "proj-1",
          kind: "current_focus_summary",
          content: "Ship observer-reflector automation | Phase 3 in progress",
          derivedFrom: ["digest-1"],
          generationMetadata: {},
          createdBy: "user-1",
          createdAt: "2026-04-13T00:00:00.000Z",
        },
      ],
      {
        projectId: "proj-1",
        projectOverview: "Relay project canon",
        currentObjective: "Old objective",
        stackDomain: null,
        recentProgress: "Old progress",
        decisions: [],
        constraints: [],
        openTasks: [],
        relevantTools: [],
        objectiveHistory: [],
        lastBootstrapAt: null,
        dirty: false,
        createdAt: "2026-04-13T00:00:00.000Z",
        updatedAt: "2026-04-13T00:00:00.000Z",
      },
    )

    expect(result.state?.currentObjective).toBe("Ship observer-reflector automation.")
    expect(result.latestCurrentFocusSummary).toContain("Phase 3")
    expect(result.tentativeEntries).toHaveLength(1)
  })
})
