import { describe, expect, it } from "vitest"

import type { CanonEntryRow, MemoryItemRow, ProjectStateRow, ProjectSummarySnapshotRow } from "@relay/shared"

import { deriveMemoryCompactionAction } from "./compaction-service"

const baseMemory = (overrides: Partial<MemoryItemRow> = {}): MemoryItemRow => ({
  id: "mem-1",
  projectId: "proj-1",
  sourceTurnId: null,
  type: "note",
  title: null,
  content: "Ship the benchmark harness update.",
  pinned: false,
  isArchived: false,
  sortOrder: null,
  tags: [],
  metadata: {},
  createdBy: "user-1",
  createdAt: "2026-04-01T00:00:00.000Z",
  updatedAt: "2026-04-01T00:00:00.000Z",
  sourceSurface: "mcp",
  sourceConversationId: null,
  sourceUrl: null,
  capturedAt: "2026-04-01T00:00:00.000Z",
  derivedFrom: null,
  embedding: null,
  embeddingModel: null,
  forgetAfter: null,
  lastReaffirmedAt: null,
  ...overrides,
})

const baseCanon = (overrides: Partial<CanonEntryRow> = {}): CanonEntryRow => ({
  id: "canon-1",
  projectId: "proj-1",
  kind: "decision",
  title: null,
  content: "Use the benchmark harness update.",
  status: "active",
  confidence: 0.8,
  lockedByUser: false,
  autoGenerated: true,
  validFrom: null,
  validUntil: null,
  lastVerifiedAt: null,
  supersedesEntryId: null,
  metadata: {},
  createdBy: "user-1",
  updatedBy: null,
  createdAt: "2026-04-01T00:00:00.000Z",
  updatedAt: "2026-04-01T00:00:00.000Z",
  ...overrides,
})

const baseSummary = (overrides: Partial<ProjectSummarySnapshotRow> = {}): ProjectSummarySnapshotRow => ({
  id: "summary-1",
  projectId: "proj-1",
  kind: "project_summary",
  content: "Ship the benchmark harness update and compare results.",
  derivedFrom: ["digest-1"],
  generationMetadata: {},
  createdBy: "user-1",
  createdAt: "2026-04-10T00:00:00.000Z",
  ...overrides,
})

const baseState: ProjectStateRow = {
  projectId: "proj-1",
  projectOverview: null,
  currentObjective: null,
  stackDomain: null,
  recentProgress: null,
  decisions: [],
  constraints: [],
  openTasks: [],
  relevantTools: [],
  objectiveHistory: [],
  lastBootstrapAt: null,
  dirty: false,
  createdAt: "2026-04-01T00:00:00.000Z",
  updatedAt: "2026-04-01T00:00:00.000Z",
}

describe("deriveMemoryCompactionAction", () => {
  it("archives completed stale tasks", () => {
    const action = deriveMemoryCompactionAction({
      item: baseMemory({ type: "task", content: "Done: ship the benchmark harness update." }),
      canonEntries: [],
      snapshots: [],
      state: baseState,
    })

    expect(action.type).toBe("archive")
    expect(action.state).toBe("completed")
  })

  it("demotes canon-covered decisions", () => {
    const action = deriveMemoryCompactionAction({
      item: baseMemory({ type: "decision", content: "Use the benchmark harness update." }),
      canonEntries: [baseCanon({ kind: "decision", content: "Use the benchmark harness update." })],
      snapshots: [],
      state: baseState,
    })

    expect(action.type).toBe("demote")
    expect(action.state).toBe("covered_by_canon")
  })

  it("archives very old summary-covered notes", () => {
    const action = deriveMemoryCompactionAction({
      item: baseMemory({ type: "note", content: "Ship the benchmark harness update and compare results", updatedAt: "2024-01-01T00:00:00.000Z" }),
      canonEntries: [],
      snapshots: [baseSummary({ content: "Ship the benchmark harness update and compare results" })],
      state: baseState,
    })

    expect(action.type).toBe("archive")
    expect(action.state).toBe("covered_by_summary")
  })

  it("keeps pinned items even if covered", () => {
    const action = deriveMemoryCompactionAction({
      item: baseMemory({ pinned: true, type: "decision", content: "Use the benchmark harness update." }),
      canonEntries: [baseCanon({ kind: "decision", content: "Use the benchmark harness update." })],
      snapshots: [baseSummary()],
      state: baseState,
    })

    expect(action.type).toBe("keep")
  })
})
