import { describe, expect, it, vi } from "vitest"

import type { RepositoryBundle } from "@relay/db"
import type { CanonEntryRow, MemoryItemRow, ProjectStateRow, ProjectSummarySnapshotRow, WorkSessionCheckpointWithSessionRow } from "@relay/shared"

import { runContinuityMaintenanceForProjectWithRepositories } from "./continuity-maintenance-service"

function makeMemory(overrides: Partial<MemoryItemRow> = {}): MemoryItemRow {
  return {
    id: "mem-1",
    projectId: "proj-1",
    sourceTurnId: null,
    type: "decision",
    title: null,
    content: "Use the benchmark harness update.",
    pinned: false,
    isArchived: false,
    sortOrder: null,
    tags: [],
    metadata: {},
    createdBy: "user-1",
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-04-01T00:00:00.000Z",
    sourceSurface: "mcp",
    sourceConversationId: null,
    sourceUrl: null,
    capturedAt: "2026-04-01T00:00:00.000Z",
    derivedFrom: null,
    embedding: null,
    embeddingModel: null,
    forgetAfter: null,
    lastReaffirmedAt: null,
    ...overrides,
  }
}

function makeCanon(overrides: Partial<CanonEntryRow> = {}): CanonEntryRow {
  return {
    id: "canon-1",
    projectId: "proj-1",
    kind: "decision",
    title: null,
    content: "Use the benchmark harness update.",
    status: "active",
    confidence: 0.8,
    lockedByUser: false,
    autoGenerated: true,
    validFrom: null,
    validUntil: null,
    lastVerifiedAt: null,
    supersedesEntryId: null,
    metadata: {},
    createdBy: "user-1",
    updatedBy: null,
    createdAt: "2026-04-01T00:00:00.000Z",
    updatedAt: "2026-04-01T00:00:00.000Z",
    ...overrides,
  }
}

function makeSummary(overrides: Partial<ProjectSummarySnapshotRow> = {}): ProjectSummarySnapshotRow {
  return {
    id: "sum-1",
    projectId: "proj-1",
    kind: "project_summary",
    content: "Use the benchmark harness update and compare results.",
    derivedFrom: ["digest-1"],
    generationMetadata: {},
    createdBy: "user-1",
    createdAt: "2026-04-10T00:00:00.000Z",
    ...overrides,
  }
}

function makeRepositories(input: {
  memoryItems: MemoryItemRow[]
  canonEntries?: CanonEntryRow[]
  summaries?: ProjectSummarySnapshotRow[]
  state?: ProjectStateRow | null
  checkpoints?: WorkSessionCheckpointWithSessionRow[]
}) {
  const updates: Array<{ id: string; patch: Record<string, unknown> }> = []
  const bootstrapClear = vi.fn(async () => undefined)
  const repositories = {
    memory: {
      listByProject: vi.fn(async () => input.memoryItems),
      update: vi.fn(async (id: string, patch: Record<string, unknown>) => {
        updates.push({ id, patch })
        return undefined
      }),
      reaffirm: vi.fn(async () => undefined),
    },
    workSessionCheckpoints: {
      listRecentByProject: vi.fn(async () => input.checkpoints ?? []),
    },
    canonEntries: {
      listByProject: vi.fn(async () => input.canonEntries ?? []),
    },
    projectSummarySnapshots: {
      listLatestByProject: vi.fn(async () => input.summaries ?? []),
    },
    projectState: {
      getByProject: vi.fn(async () => input.state ?? null),
    },
    projectSettings: {
      getByProject: vi.fn(async () => null),
    },
    workSessions: {
      markStaleOlderThan: vi.fn(async () => 0),
    },
    bootstrapPackets: {
      clearProject: bootstrapClear,
    },
  } as unknown as RepositoryBundle

  return { repositories, updates, bootstrapClear }
}

describe("runContinuityMaintenanceForProjectWithRepositories", () => {
  it("demotes canon-covered decision memory", async () => {
    const { repositories, updates } = makeRepositories({
      memoryItems: [makeMemory()],
      canonEntries: [makeCanon()],
      summaries: [],
    })

    await runContinuityMaintenanceForProjectWithRepositories(repositories, "proj-1")

    expect(updates.some((update) => (update.patch.metadata as Record<string, unknown>)?.compactionState === "covered_by_canon")).toBe(true)
  })

  it("archives completed stale tasks", async () => {
    const { repositories, updates } = makeRepositories({
      memoryItems: [makeMemory({ type: "task", content: "Done: ship the benchmark harness update." })],
      summaries: [makeSummary()],
      state: {
        projectId: "proj-1",
        projectOverview: null,
        currentObjective: null,
        stackDomain: null,
        recentProgress: null,
        decisions: [],
        constraints: [],
        openTasks: [],
        relevantTools: [],
        objectiveHistory: [],
        lastBootstrapAt: null,
        dirty: false,
        createdAt: "2026-04-01T00:00:00.000Z",
        updatedAt: "2026-04-01T00:00:00.000Z",
      },
    })

    await runContinuityMaintenanceForProjectWithRepositories(repositories, "proj-1")

    expect(updates.some((update) => update.patch.isArchived === true)).toBe(true)
  })
})
