import { createRepositoryBundle } from "@relay/db"
import type {
  CanonEntryDto,
  CanonEntryKind,
  CanonEntryRow,
  CanonEntryStatus,
  CanonEvidenceDto,
  CanonEvidenceRow,
} from "@relay/shared"
import {
  createCanonEntrySchema,
  sortCanonEntriesByPriority,
  updateCanonEntrySchema,
} from "@relay/shared"

import { NotFoundError } from "@/server/http/errors"

function toCanonEvidenceDto(evidence: CanonEvidenceRow): CanonEvidenceDto {
  return {
    id: evidence.id,
    sourceKind: evidence.sourceKind,
    sourceId: evidence.sourceId,
    excerpt: evidence.excerpt,
    weight: evidence.weight,
    createdAt: evidence.createdAt,
  }
}

function toCanonEntryDto(entry: CanonEntryRow, evidence?: CanonEvidenceDto[]): CanonEntryDto {
  return {
    id: entry.id,
    kind: entry.kind,
    title: entry.title,
    content: entry.content,
    status: entry.status,
    confidence: entry.confidence,
    lockedByUser: entry.lockedByUser,
    autoGenerated: entry.autoGenerated,
    validFrom: entry.validFrom,
    validUntil: entry.validUntil,
    lastVerifiedAt: entry.lastVerifiedAt,
    supersedesEntryId: entry.supersedesEntryId,
    metadata: entry.metadata,
    createdBy: entry.createdBy,
    updatedBy: entry.updatedBy,
    createdAt: entry.createdAt,
    updatedAt: entry.updatedAt,
    evidence,
  }
}

export async function listProjectCanon(
  userId: string,
  projectId: string,
  options?: {
    kinds?: CanonEntryKind[]
    statuses?: CanonEntryStatus[]
    includeEvidence?: boolean
  },
): Promise<CanonEntryDto[]> {
  const repositories = createRepositoryBundle(userId)
  const entries = await repositories.canonEntries.listByProject(projectId, {
    kinds: options?.kinds,
    statuses: options?.statuses,
  })

  const ordered = sortCanonEntriesByPriority(entries)

  if (!options?.includeEvidence) {
    return ordered.map((entry) => toCanonEntryDto(entry))
  }

  return Promise.all(
    ordered.map(async (entry) => {
      const evidence = await repositories.canonEvidence.listByEntry(entry.id)
      return toCanonEntryDto(entry, evidence.map(toCanonEvidenceDto))
    }),
  )
}

export async function getCanonEntry(userId: string, projectId: string, entryId: string): Promise<CanonEntryDto | null> {
  const repositories = createRepositoryBundle(userId)
  const entry = await repositories.canonEntries.getById(entryId)
  if (!entry || entry.projectId !== projectId) return null
  const evidence = await repositories.canonEvidence.listByEntry(entry.id)
  return toCanonEntryDto(entry, evidence.map(toCanonEvidenceDto))
}

export async function createCanonEntry(userId: string, input: unknown): Promise<CanonEntryDto> {
  const repositories = createRepositoryBundle(userId)
  const parsed = createCanonEntrySchema.parse(input)

  return repositories.provider.transaction(async (provider) => {
    const tx = createRepositoryBundle(userId, provider)
    const entry = await tx.canonEntries.create(userId, {
      projectId: parsed.projectId,
      kind: parsed.kind,
      title: parsed.title ?? null,
      content: parsed.content,
      status: parsed.status ?? "active",
      confidence: parsed.confidence ?? 0.7,
      lockedByUser: parsed.lockedByUser ?? false,
      autoGenerated: parsed.autoGenerated ?? false,
      validFrom: parsed.validFrom ?? null,
      validUntil: parsed.validUntil ?? null,
      lastVerifiedAt: parsed.lastVerifiedAt ?? null,
      supersedesEntryId: parsed.supersedesEntryId ?? null,
      metadata: parsed.metadata ?? {},
    })

    const evidence = await tx.canonEvidence.replaceForEntry(parsed.projectId, entry.id, parsed.evidence ?? [])
    await tx.bootstrapPackets.clearProject(parsed.projectId)

    return toCanonEntryDto(entry, evidence.map(toCanonEvidenceDto))
  })
}

export async function updateCanonEntry(userId: string, projectId: string, entryId: string, input: unknown): Promise<CanonEntryDto> {
  const repositories = createRepositoryBundle(userId)
  const parsed = updateCanonEntrySchema.parse(input)

  return repositories.provider.transaction(async (provider) => {
    const tx = createRepositoryBundle(userId, provider)
    const existing = await tx.canonEntries.getById(entryId)
    if (!existing || existing.projectId !== projectId) {
      throw new NotFoundError("Canon entry not found.")
    }

    const entry = await tx.canonEntries.update(userId, entryId, parsed)
    const evidence = parsed.evidence
      ? await tx.canonEvidence.replaceForEntry(projectId, entry.id, parsed.evidence)
      : await tx.canonEvidence.listByEntry(entry.id)

    await tx.bootstrapPackets.clearProject(projectId)

    return toCanonEntryDto(entry, evidence.map(toCanonEvidenceDto))
  })
}
