import { describe, expect, it } from "vitest"

import { buildCurrentPreviousHint, buildReasoningEvidenceTable, buildTemporalResolutionHint } from "./reasoning-assembly-service"

describe("reasoning assembly service", () => {
  it("derives current, previous, and changedAt by recency", () => {
    const hint = buildCurrentPreviousHint([
      {
        id: "older",
        projectId: "proj-1",
        kind: "objective",
        title: null,
        content: "Old objective",
        status: "superseded",
        confidence: 0.6,
        lockedByUser: false,
        autoGenerated: true,
        validFrom: "2026-04-01T00:00:00.000Z",
        validUntil: "2026-04-05T00:00:00.000Z",
        lastVerifiedAt: null,
        supersedesEntryId: null,
        metadata: {},
        createdBy: "user-1",
        updatedBy: null,
        createdAt: "2026-04-01T00:00:00.000Z",
        updatedAt: "2026-04-01T00:00:00.000Z",
      },
      {
        id: "current",
        projectId: "proj-1",
        kind: "objective",
        title: null,
        content: "Current objective",
        status: "active",
        confidence: 0.9,
        lockedByUser: false,
        autoGenerated: true,
        validFrom: "2026-04-06T00:00:00.000Z",
        validUntil: null,
        lastVerifiedAt: null,
        supersedesEntryId: "older",
        metadata: {},
        createdBy: "user-1",
        updatedBy: null,
        createdAt: "2026-04-06T00:00:00.000Z",
        updatedAt: "2026-04-06T00:00:00.000Z",
      },
    ])

    expect(hint.current?.id).toBe("current")
    expect(hint.previous?.id).toBe("older")
    expect(hint.changedAt).toBe("2026-04-06T00:00:00.000Z")
  })

  it("builds typed evidence rows", () => {
    const rows = buildReasoningEvidenceTable({
      query: {
        normalizedQuery: "how many tasks",
        stateIntent: "general",
        reasoningMode: "aggregation",
        projectStateIntent: false,
        canonKinds: [],
        historicalAt: null,
        sourceDateRange: undefined,
        asksCountOrTotal: true,
        asksOrder: false,
        asksDuration: false,
      },
      canonResults: [],
      memoryResults: [
        {
          id: "mem-1",
          projectId: "proj-1",
          sourceTurnId: null,
          type: "task",
          title: null,
          content: "Task count: 12",
          pinned: false,
          isArchived: false,
          sortOrder: null,
          tags: [],
          metadata: {},
          createdBy: "user-1",
          createdAt: "2026-04-12T00:00:00.000Z",
          updatedAt: "2026-04-12T00:00:00.000Z",
          sourceSurface: "mcp",
          sourceConversationId: null,
          sourceUrl: null,
          capturedAt: "2026-04-12T00:00:00.000Z",
          derivedFrom: null,
          embedding: null,
          embeddingModel: null,
          forgetAfter: null,
          lastReaffirmedAt: null,
        },
      ],
    })

    expect(rows[0]?.typedFact?.numericValue).toBe(12)
  })

  it("builds temporal resolution hints from evidence rows", () => {
    const hint = buildTemporalResolutionHint([
      { source: "memory", sourceId: "a", kind: "note", when: "2026-04-01T00:00:00.000Z", content: "a", typedFact: null },
      { source: "memory", sourceId: "b", kind: "note", when: "2026-04-10T00:00:00.000Z", content: "b", typedFact: null },
    ])

    expect(hint.elapsedDays).toBe(9)
    expect(hint.order).toBe("before")
  })
})
