import type { CanonEntryRow, CanonEvidenceRow, ProjectSummarySnapshotRow } from "@relay/shared"

import { decryptJsonbIfNeeded, decryptTextIfNeeded } from "../utils/encrypted-text"
import { toTimestamp } from "./timestamp"

export function toCanonEntryRow(record: Record<string, unknown>): CanonEntryRow {
  return {
    id: String(record.id),
    projectId: String(record.project_id),
    kind: record.kind as CanonEntryRow["kind"],
    title: record.title ? decryptTextIfNeeded(String(record.title)) : null,
    content: decryptTextIfNeeded(String(record.content)),
    status: record.status as CanonEntryRow["status"],
    confidence: Number(record.confidence ?? 0),
    lockedByUser: Boolean(record.locked_by_user),
    autoGenerated: Boolean(record.auto_generated),
    validFrom: record.valid_from ? toTimestamp(record.valid_from) : null,
    validUntil: record.valid_until ? toTimestamp(record.valid_until) : null,
    lastVerifiedAt: record.last_verified_at ? toTimestamp(record.last_verified_at) : null,
    supersedesEntryId: record.supersedes_entry_id ? String(record.supersedes_entry_id) : null,
    metadata: (record.metadata as Record<string, unknown>) ?? {},
    createdBy: String(record.created_by),
    updatedBy: record.updated_by ? String(record.updated_by) : null,
    createdAt: toTimestamp(record.created_at),
    updatedAt: toTimestamp(record.updated_at),
  }
}

export function toCanonEvidenceRow(record: Record<string, unknown>): CanonEvidenceRow {
  return {
    id: String(record.id),
    projectId: String(record.project_id),
    canonEntryId: String(record.canon_entry_id),
    sourceKind: record.source_kind as CanonEvidenceRow["sourceKind"],
    sourceId: String(record.source_id),
    excerpt: record.excerpt ? decryptTextIfNeeded(String(record.excerpt)) : null,
    weight: Number(record.weight ?? 0),
    createdAt: toTimestamp(record.created_at),
  }
}

export function toProjectSummarySnapshotRow(record: Record<string, unknown>): ProjectSummarySnapshotRow {
  const derivedFrom = decryptJsonbIfNeeded(record.derived_from)

  return {
    id: String(record.id),
    projectId: String(record.project_id),
    kind: record.kind as ProjectSummarySnapshotRow["kind"],
    content: decryptTextIfNeeded(String(record.content)),
    derivedFrom: Array.isArray(derivedFrom) ? derivedFrom.filter((value): value is string => typeof value === "string") : [],
    generationMetadata: (record.generation_metadata as Record<string, unknown>) ?? {},
    createdBy: record.created_by ? String(record.created_by) : null,
    createdAt: toTimestamp(record.created_at),
  }
}
