import { describe, expect, it } from "vitest"

import { computeCanonPriorityScore, sortCanonEntriesByPriority } from "./canon"

describe("canon priority scoring", () => {
  it("prioritizes locked user canon over auto-generated active canon", () => {
    const locked = computeCanonPriorityScore({
      status: "active",
      lockedByUser: true,
      autoGenerated: false,
      confidence: 0.4,
      updatedAt: "2026-04-12T00:00:00.000Z",
    })
    const auto = computeCanonPriorityScore({
      status: "active",
      lockedByUser: false,
      autoGenerated: true,
      confidence: 0.95,
      updatedAt: "2026-04-12T00:00:00.000Z",
    })

    expect(locked).toBeGreaterThan(auto)
  })

  it("prioritizes active canon over superseded canon", () => {
    const ranked = sortCanonEntriesByPriority([
      { id: "old", status: "superseded", confidence: 1, updatedAt: "2026-04-12T00:00:00.000Z" },
      { id: "current", status: "active", confidence: 0.6, updatedAt: "2026-04-11T00:00:00.000Z" },
    ])

    expect((ranked[0] as { id: string }).id).toBe("current")
  })

  it("prefers user-authored canon over auto-generated tentative canon when otherwise similar", () => {
    const ranked = sortCanonEntriesByPriority([
      { id: "machine", status: "tentative", autoGenerated: true, confidence: 0.95, updatedAt: "2026-04-12T00:00:00.000Z" },
      { id: "human", status: "tentative", autoGenerated: false, confidence: 0.7, updatedAt: "2026-04-10T00:00:00.000Z" },
    ])

    expect((ranked[0] as { id: string }).id).toBe("human")
  })
})
