import type { CanonEntryStatus } from "../types/database"

const STATUS_WEIGHT: Record<CanonEntryStatus, number> = {
  active: 100,
  tentative: 70,
  disputed: 35,
  stale: 20,
  resolved: 10,
  superseded: 0,
}

export interface CanonEntryForPriority {
  status: CanonEntryStatus
  lockedByUser?: boolean
  autoGenerated?: boolean
  confidence?: number
  updatedAt?: string | null
  validUntil?: string | null
}

export function computeCanonPriorityScore(entry: CanonEntryForPriority): number {
  const confidence = Math.max(0, Math.min(1, entry.confidence ?? 0))
  const freshness = entry.updatedAt ? Math.max(0, Date.parse(entry.updatedAt) || 0) / 1_000_000_000_000 : 0
  const activeValidityBonus = entry.validUntil ? -5 : 5

  return (
    (STATUS_WEIGHT[entry.status] ?? 0) +
    (entry.lockedByUser ? 1000 : 0) +
    (entry.autoGenerated ? 0 : 50) +
    confidence * 100 +
    activeValidityBonus +
    freshness
  )
}

export function sortCanonEntriesByPriority<T extends CanonEntryForPriority>(entries: T[]): T[] {
  return [...entries].sort((left, right) => computeCanonPriorityScore(right) - computeCanonPriorityScore(left))
}
